version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .aws/.env
    volumes:
      - db-data:/var/lib/mysql
    #   - ./db:/docker-entrypoint-initdb.d
    networks:
      - internal
    ports:
      - "33208:3306"

  drupal:
    image: drupal:8.7.8-fpm-alpine
    container_name: drupal
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - ./:/var/www/html

  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    #   - certbot-etc:/etc/letsencrypt
    networks:
      - external

#   certbot:
#     depends_on:
#       - webserver
#     image: certbot/certbot
#     container_name: certbot
#     volumes:
#       - certbot-etc:/etc/letsencrypt
#       - drupal-data:/var/www/html
#     command: certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --staging -d your_domain -d www.your_domain

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
#   drupal-data:
  db-data:
#   certbot-etc: